In [2]:
from utilities.utils import SectoralDiffReport, NonEnergySectoralDiffReport, SSPModelForCalibration, HelperFunctions
from sisepuede.manager.sisepuede_examples import SISEPUEDEExamples
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
# Initialize helper functions
helper_functions = HelperFunctions()

In [40]:
input_df = pd.read_csv('../data/real_data.csv')
input_df.head()

,region,iso_code3,period,area_gnrl_country_ha,avgload_trns_freight_tonne_per_vehicle_aviation,avgload_trns_freight_tonne_per_vehicle_rail_freight,avgload_trns_freight_tonne_per_vehicle_road_heavy_freight,avgload_trns_freight_tonne_per_vehicle_water_borne,avgmass_lvst_animal_buffalo_kg,avgmass_lvst_animal_cattle_dairy_kg,...,yf_agrc_fruits_tonne_ha,yf_agrc_herbs_and_other_perennial_crops_tonne_ha,yf_agrc_nuts_tonne_ha,yf_agrc_other_annual_tonne_ha,yf_agrc_other_woody_perennial_tonne_ha,yf_agrc_pulses_tonne_ha,yf_agrc_rice_tonne_ha,yf_agrc_sugar_cane_tonne_ha,yf_agrc_tubers_tonne_ha,yf_agrc_vegetables_and_vines_tonne_ha
0,croatia,HRV,0,8807000,70,2923,31.751466,6468,315,508,...,5.546667,28.8742,0.602367,1.930675,0.5205,2.638183,0,0,35.76480,21.067738
1,croatia,HRV,1,8807000,70,2923,31.751466,6468,315,508,...,5.555383,29.6558,0.479900,2.304050,0.7342,3.256933,0,0,47.57660,20.412554
2,croatia,HRV,2,8807000,70,2923,31.751466,6468,315,508,...,4.304906,30.0390,0.360400,2.075950,0.8615,3.199083,0,0,41.09780,22.329531
3,croatia,HRV,3,8807000,70,2923,31.751466,6468,315,508,...,6.272229,30.0390,0.160300,2.662133,0.9852,3.266680,0,0,37.42445,21.505800
4,croatia,HRV,4,8807000,70,2923,31.751466,6468,315,508,...,5.878853,30.0390,0.196325,2.543567,0.9045,4.068040,0,0,39.81490,21.874247

In [41]:
# Load input dataset
examples = SISEPUEDEExamples()
cr = examples("input_data_frame")

# Add missing columns and reformat the input datas
df_input = input_df.rename(columns={'period': 'time_period'})
df_input = helper_functions.add_missing_cols(cr, df_input.copy())
df_input = df_input.drop(columns='iso_code3')

# Subset df_input to the input rows amount
df_input = df_input.iloc[:10]

df_input

,region,time_period,area_gnrl_country_ha,avgload_trns_freight_tonne_per_vehicle_aviation,avgload_trns_freight_tonne_per_vehicle_rail_freight,avgload_trns_freight_tonne_per_vehicle_road_heavy_freight,avgload_trns_freight_tonne_per_vehicle_water_borne,avgmass_lvst_animal_buffalo_kg,avgmass_lvst_animal_cattle_dairy_kg,avgmass_lvst_animal_cattle_nondairy_kg,...,nemomod_entc_input_activity_ratio_fuel_production_fp_hydrogen_electrolysis_water,nemomod_entc_input_activity_ratio_fuel_production_fp_hydrogen_reformation_ccs_electricity,energydensity_gravimetric_enfu_gj_per_tonne_fuel_ammonia,energydensity_gravimetric_enfu_gj_per_tonne_fuel_water,frac_trns_fuelmix_water_borne_ammonia,nemomod_entc_output_activity_ratio_fuel_production_fp_ammonia_production_ammonia,nemomod_entc_output_activity_ratio_fuel_production_fp_hydrogen_reformation_ccs_hydrogen,nemomod_entc_frac_min_share_production_fp_hydrogen_reformation_ccs,nemomod_entc_input_activity_ratio_fuel_production_fp_hydrogen_reformation_ccs_natural_gas,nemomod_entc_input_activity_ratio_fuel_production_fp_hydrogen_reformation_ccs_oil
0,croatia,0,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
1,croatia,1,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
2,croatia,2,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
3,croatia,3,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
4,croatia,4,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
5,croatia,5,8807000,70,2923,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
6,croatia,6,8807000,70,4082,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
7,croatia,7,8807000,70,4082,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
8,croatia,8,8807000,70,4082,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0
9,croatia,9,8807000,70,4082,31.751466,6468,315,508,303,...,0.000004,0,18.6,0.00005,0.0,1,1,0.0,1.315,0.0

In [7]:
# Initialize the SSP model
ssp_model = SSPModelForCalibration(energy_model_flag=False)

2025-02-12 16:23:13,141 - INFO - Successfully initialized SISEPUEDEFileStructure.
2025-02-12 16:23:13,144 - WARNING - Missing key dict_dimensional_keys: key time_series not found. Tables that rely on the time_series will not have index checking.
2025-02-12 16:23:13,145 - INFO - 	Setting export engine to 'csv'.
2025-02-12 16:23:13,146 - WARNING - No index fields defined. Index field values will not be checked when writing to tables.
2025-02-12 16:23:13,147 - INFO - Successfully instantiated table ANALYSIS_METADATA
2025-02-12 16:23:13,148 - WARNING - No index fields found in ATTRIBUTE_DESIGN. Initializing index fields.
2025-02-12 16:23:13,149 - INFO - Successfully instantiated table ATTRIBUTE_DESIGN
2025-02-12 16:23:13,150 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES. Initializing index fields.
2025-02-12 16:23:13,151 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_EXOGENOUS_UNCERTAINTIES
2025-02-12 16:23:13,152 - WARNING - No index fields found in ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS. Initializing index fields.
2025-02-12 16:23:13,153 - INFO - Successfully instantiated table ATTRIBUTE_LHC_SAMPLES_LEVER_EFFECTS
2025-02-12 16:23:13,153 - WARNING - No index fields found in ATTRIBUTE_PRIMARY. Initializing index fields.
2025-02-12 16:23:13,154 - INFO - Successfully instantiated table ATTRIBUTE_PRIMARY
2025-02-12 16:23:13,155 - WARNING - No index fields found in ATTRIBUTE_STRATEGY. Initializing index fields.
2025-02-12 16:23:13,155 - INFO - Successfully instantiated table ATTRIBUTE_STRATEGY
2025-02-12 16:23:13,156 - WARNING - No index fields found in MODEL_BASE_INPUT_DATABASE. Initializing index fields.
2025-02-12 16:23:13,157 - INFO - Successfully instantiated table MODEL_BASE_INPUT_DATABASE
2025-02-12 16:23:13,157 - WARNING - No index fields found in MODEL_INPUT. Initializing index fields.
2025-02-12 16:23:13,158 - INFO - Successfully instantiated table MODEL_INPUT
2025-02-12 16:23:13,159 - WARNING - No index fields found in MODEL_OUTPUT. Initializing index fields.
2025-02-12 16:23:13,160 - INFO - Successfully instantiated table MODEL_OUTPUT
2025-02-12 16:23:13,160 - INFO - SISEPUEDEOutputDatabase successfully initialized IterativeDatabase.
2025-02-12 16:23:13,161 - INFO - Successfully initialized database with:
	type:	csv
	analysis id:	sisepuede_run_2025-02-12T16:23:12.340195
	fp_base_output:	/home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2025-02-12T16;23;12.340195/sisepuede_run_2025-02-12T16;23;12.340195_output_database
2025-02-12 16:23:13,162 - INFO - Running SISEPUEDE under template data mode 'calibrated'.
2025-02-12 16:23:13,163 - INFO - Initializing BaseInputDatabase
2025-02-12 16:23:14,446 - INFO - Initializing FutureTrajectories
2025-02-12 16:23:20,511 - INFO - Instantiating 1392 sampling units.
2025-02-12 16:23:20,580 - INFO - Iteration 0 complete.
2025-02-12 16:23:30,607 - INFO - Iteration 250 complete.
2025-02-12 16:23:35,497 - INFO - Iteration 500 complete.
2025-02-12 16:23:40,447 - INFO - Iteration 750 complete.
2025-02-12 16:23:45,630 - INFO - Iteration 1000 complete.
2025-02-12 16:23:50,467 - INFO - Iteration 1250 complete.
2025-02-12 16:23:53,472 - INFO - 	1392 sampling units complete in 32.96 seconds.
2025-02-12 16:23:53,478 - INFO - 	FutureTrajectories for 'costa_rica' complete.
2025-02-12 16:23:53,479 - INFO - Initializing LHSDesign
2025-02-12 16:23:53,480 - INFO - LHSDesign.fields_factors_l reset successful.
2025-02-12 16:23:53,480 - INFO - LHSDesign.fields_factors_x reset successful.
2025-02-12 16:23:53,492 - INFO - 	LHSDesign for region 'costa_rica' complete.
2025-02-12 16:23:53,493 - INFO - Generating primary keys (values of primary_id)...
2025-02-12 16:23:53,494 - INFO - Successfully initialized SISEPUEDEExperimentalManager.
2025-02-12 16:23:53,495 - INFO - Successfully initialized NemoMod temporary database path as /home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/tmp/nemomod_intermediate_database.sqlite.
2025-02-12 16:23:53,496 - INFO - Set Julia directory for modules and environment to '/home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/julia'.
2025-02-12 16:23:53,600 - INFO - Successfully initialized SISEPUEDEModels.
2025-02-12 16:23:53,608 - INFO - Table ANALYSIS_METADATA successfully written to /home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2025-02-12T16;23;12.340195/sisepuede_run_2025-02-12T16;23;12.340195_output_database/ANALYSIS_METADATA.csv.
2025-02-12 16:23:53,611 - INFO - Table ATTRIBUTE_DESIGN successfully written to /home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2025-02-12T16;23;12.340195/sisepuede_run_2025-02-12T16;23;12.340195_output_database/ATTRIBUTE_DESIGN.csv.
2025-02-12 16:23:53,615 - INFO - Table ATTRIBUTE_STRATEGY successfully written to /home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2025-02-12T16;23;12.340195/sisepuede_run_2025-02-12T16;23;12.340195_output_database/ATTRIBUTE_STRATEGY.csv.
2025-02-12 16:23:53,974 - INFO - Table MODEL_BASE_INPUT_DATABASE successfully written to /home/tony-ubuntu/anaconda3/envs/opt_env/lib/python3.11/site-packages/sisepuede/out/sisepuede_run_2025-02-12T16;23;12.340195/sisepuede_run_2025-02-12T16;23;12.340195_output_database/MODEL_BASE_INPUT_DATABASE.csv.

In [42]:
output_df = ssp_model.run_ssp_simulation(df_input)

2025-02-12 16:44:48,414 - INFO - Running AFOLU model

2025-02-12 16:44:48,611 - INFO - AFOLU model run successfully completed
2025-02-12 16:44:48,613 - INFO - Running CircularEconomy model
2025-02-12 16:44:48,684 - INFO - CircularEconomy model run successfully completed
2025-02-12 16:44:48,685 - INFO - Running IPPU model
2025-02-12 16:44:48,774 - INFO - IPPU model run successfully completed
2025-02-12 16:44:48,775 - INFO - Running Energy model (EnergyConsumption without Fugitive Emissions)
2025-02-12 16:44:48,799 - DEBUG - Missing elasticity information found in 'project_energy_consumption_by_fuel_from_effvars': using specified future demands.
2025-02-12 16:44:48,904 - INFO - EnergyConsumption without Fugitive Emissions model run successfully completed
2025-02-12 16:44:48,905 - INFO - Running Energy (Fugitive Emissions)
2025-02-12 16:44:48,933 - ERROR - Error running Fugitive Emissions from Energy model: 'NoneType' object has no attribute 'to_numpy'
2025-02-12 16:44:48,934 - INFO - Appending Socioeconomic outputs
2025-02-12 16:44:48,945 - INFO - Socioeconomic outputs successfully appended.

In [43]:
sdr = SectoralDiffReport('misc/sectoral_reports', iso_alpha_3='HRV', init_year=2015, ref_year=2022)

In [44]:
sdr.edgar_data_etl(file_path='misc/sectoral_reports/CSC-GHG_emissions-April2024_to_calibrate.csv')

                            Edgar_Class  Year  Edgar_Values
0                    AG - Livestock:CH4  2022      1.610948
1                    AG - Livestock:N2O  2022      0.100881
2                        AG - Crops:CH4  2022      0.000115
3                        AG - Crops:CO2  2022      0.106978
4                        AG - Crops:N2O  2022      1.300449
5                     EN - Building:CH4  2022      0.332792
6                     EN - Building:CO2  2022      2.603821
7                     EN - Building:N2O  2022      0.106908
8             EN - Electricity/Heat:CH4  2022      0.010481
9             EN - Electricity/Heat:CO2  2022      2.522588
10            EN - Electricity/Heat:N2O  2022      0.013915
11          EN - Fugitive Emissions:CH4  2022      0.460170
12          EN - Fugitive Emissions:CO2  2022      0.798061
13          EN - Fugitive Emissions:N2O  2022      0.001021
14  EN - Manufacturing/Construction:CH4  2022      0.005527
15  EN - Manufacturing/Construction:CO2  2022      2.370070
16  EN - Manufacturing/Construction:N2O  2022      0.007447
17              EN - Transportation:CH4  2022      0.011384
18              EN - Transportation:CO2  2022      6.654934
19              EN - Transportation:N2O  2022      0.068342
20        IN - Industrial Processes:CH4  2022      0.001428
21        IN - Industrial Processes:CO2  2022      2.168521
22       IN - Industrial Processes:HCFC  2022      0.004950
23        IN - Industrial Processes:HFC  2022      0.551213
24        IN - Industrial Processes:N2O  2022      0.784469
25        IN - Industrial Processes:PFC  2022      0.000000
26        IN - Industrial Processes:SF6  2022      0.005196
27              Waste - Solid Waste:CH4  2022      1.009457
28              Waste - Solid Waste:CO2  2022      0.000000
29              Waste - Solid Waste:N2O  2022      0.009818
30     Waste - Wastewater Treatment:CH4  2022      0.428962
31     Waste - Wastewater Treatment:N2O  2022      0.065935
32             LULUCF - Forest Land:CO2  2022     -6.373335
33           LULUCF - Deforestation:CO2  2022      0.023807
34            LULUCF - Organic Soil:CO2  2022      0.092259
35              LULUCF - Other Land:CO2  2022      0.774992

In [45]:
targets_df = sdr.load_emission_targets(file_path='misc/sectoral_reports/2022_emission_targets.csv')
targets_df

   Subsector  Gas                Edgar_Class  Year  Edgar_Values
0       lvst  ch4         AG - Livestock:CH4  2022      0.805474
1       lsmm  ch4         AG - Livestock:CH4  2022      0.805474
2       lsmm  n2o         AG - Livestock:N2O  2022      0.100881
3       agrc  co2             AG - Crops:CO2  2022      0.106978
4       agrc  ch4             AG - Crops:CH4  2022      0.000115
..       ...  ...                        ...   ...           ...
63      soil  co2  LULUCF - Organic Soil:CO2  2022      0.092259
64      soil  n2o  LULUCF - Organic Soil:N2O  2022      0.000000
65      ccsq  ch4                   CCSQ:CH4  2022      0.000000
66      ccsq  co2                   CCSQ:CO2  2022      0.000000
67      ccsq  n2o                   CCSQ:N2O  2022      0.000000

[68 rows x 5 columns]

In [46]:
mapping_df = pd.read_csv('misc/sectoral_reports/edgar_ssp_cw.csv')
mapping_df

,Subsector,Gas,Edgar_Class,Edgar_Subsector,Edgar_Sector,Vars
0,lvst,ch4,AG - Livestock:CH4,AG - Livestock,Agriculture,emission_co2e_ch4_lvst_entferm_buffalo:emissio...
1,lsmm,ch4,AG - Livestock:CH4,AG - Livestock,Agriculture,emission_co2e_ch4_lsmm_anaerobic_digester:emis...
2,lsmm,n2o,AG - Livestock:N2O,AG - Livestock,Agriculture,emission_co2e_n2o_lsmm_anaerobic_digester:emis...
3,agrc,co2,AG - Crops:CO2,AG - Crops,Agriculture,emission_co2e_co2_agrc_biomass_bevs_and_spices...
4,agrc,ch4,AG - Crops:CH4,AG - Crops,Agriculture,emission_co2e_ch4_agrc_anaerobicdom_rice:emiss...
...,...,...,...,...,...,...
63,soil,co2,LULUCF - Organic Soil:CO2,LULUCF - Organic Soil,"Land Use, Land Use Change, and Forestry",emission_co2e_co2_soil_lime_use:emission_co2e_...
64,soil,n2o,LULUCF - Organic Soil:N2O,LULUCF - Organic Soil,"Land Use, Land Use Change, and Forestry",emission_co2e_n2o_soil_fertilizer:emission_co2...
65,ccsq,ch4,CCSQ:CH4,CCSQ,CCSQ,emission_co2e_ch4_ccsq_direct_air_capture
66,ccsq,co2,CCSQ:CO2,CCSQ,CCSQ,emission_co2e_co2_ccsq_direct_air_capture
67,ccsq,n2o,CCSQ:N2O,CCSQ,CCSQ,emission_co2e_n2o_ccsq_direct_air_capture

In [58]:
output_df_filtered = sdr.load_simulation_output_data(output_df)
output_df_filtered

,time_period,area_agrc_crops_bevs_and_spices,area_agrc_crops_cereals,area_agrc_crops_fibers,area_agrc_crops_fruits,area_agrc_crops_herbs_and_other_perennial_crops,area_agrc_crops_nuts,area_agrc_crops_other_annual,area_agrc_crops_other_woody_perennial,area_agrc_crops_pulses,...,yield_agrc_herbs_and_other_perennial_crops_tonne,yield_agrc_nuts_tonne,yield_agrc_other_annual_tonne,yield_agrc_other_woody_perennial_tonne,yield_agrc_pulses_tonne,yield_agrc_rice_tonne,yield_agrc_sugar_cane_tonne,yield_agrc_tubers_tonne,yield_agrc_vegetables_and_vines_tonne,year
7,7,124241.137657,276356.889531,57342.063534,149461.026711,192865.783136,105259.852737,139240.334831,92915.380726,63978.876443,...,5.793495e+06,20665.140589,354167.074332,84041.961867,260268.628525,2736.0,2449.0,2.198510e+06,725876.413261,2022

In [59]:
draft_df = sdr.calculate_ssp_emission_totals(output_df_filtered, mapping_df)
draft_df

,Subsector,Gas,Edgar_Class,Edgar_Subsector,Edgar_Sector,Vars,Simulation_Values
0,lvst,ch4,AG - Livestock:CH4,AG - Livestock,Agriculture,emission_co2e_ch4_lvst_entferm_buffalo:emissio...,2.104209
1,lsmm,ch4,AG - Livestock:CH4,AG - Livestock,Agriculture,emission_co2e_ch4_lsmm_anaerobic_digester:emis...,0.042941
2,lsmm,n2o,AG - Livestock:N2O,AG - Livestock,Agriculture,emission_co2e_n2o_lsmm_anaerobic_digester:emis...,0.178724
3,agrc,co2,AG - Crops:CO2,AG - Crops,Agriculture,emission_co2e_co2_agrc_biomass_bevs_and_spices...,1.268444
4,agrc,ch4,AG - Crops:CH4,AG - Crops,Agriculture,emission_co2e_ch4_agrc_anaerobicdom_rice:emiss...,0.205360
...,...,...,...,...,...,...,...
63,soil,co2,LULUCF - Organic Soil:CO2,LULUCF - Organic Soil,"Land Use, Land Use Change, and Forestry",emission_co2e_co2_soil_lime_use:emission_co2e_...,0.437548
64,soil,n2o,LULUCF - Organic Soil:N2O,LULUCF - Organic Soil,"Land Use, Land Use Change, and Forestry",emission_co2e_n2o_soil_fertilizer:emission_co2...,1.062639
65,ccsq,ch4,CCSQ:CH4,CCSQ,CCSQ,emission_co2e_ch4_ccsq_direct_air_capture,0.000000
66,ccsq,co2,CCSQ:CO2,CCSQ,CCSQ,emission_co2e_co2_ccsq_direct_air_capture,0.000000
67,ccsq,n2o,CCSQ:N2O,CCSQ,CCSQ,emission_co2e_n2o_ccsq_direct_air_capture,0.000000

In [60]:
detailed_diff_report_agg = draft_df.groupby(['Subsector', 'Gas', 'Edgar_Class'])['Simulation_Values'].sum().reset_index()
detailed_diff_report_agg

   Subsector  Gas                       Edgar_Class  Simulation_Values
0       agrc  ch4                    AG - Crops:CH4           0.205360
1       agrc  co2                    AG - Crops:CO2           1.268444
2       agrc  n2o                    AG - Crops:N2O           0.223638
3       ccsq  ch4                          CCSQ:CH4           0.000000
4       ccsq  co2                          CCSQ:CO2           0.000000
..       ...  ...                               ...                ...
63      trww  ch4  Waste - Wastewater Treatment:CH4           0.438294
64      trww  n2o  Waste - Wastewater Treatment:N2O           0.273529
65      waso  ch4           Waste - Solid Waste:CH4           1.145807
66      waso  co2           Waste - Solid Waste:CO2           0.574465
67      waso  n2o           Waste - Solid Waste:N2O           0.000698

[68 rows x 4 columns]

In [61]:
# Merge the aggregated DataFrame with the Edgar data
detailed_diff_report_merge = pd.merge(detailed_diff_report_agg, targets_df, how='left', on=['Subsector', 'Gas', 'Edgar_Class'])
detailed_diff_report_merge

,Subsector,Gas,Edgar_Class,Simulation_Values,Year,Edgar_Values
0,agrc,ch4,AG - Crops:CH4,0.205360,2022,0.000115
1,agrc,co2,AG - Crops:CO2,1.268444,2022,0.106978
2,agrc,n2o,AG - Crops:N2O,0.223638,2022,1.300449
3,ccsq,ch4,CCSQ:CH4,0.000000,2022,0.000000
4,ccsq,co2,CCSQ:CO2,0.000000,2022,0.000000
...,...,...,...,...,...,...
63,trww,ch4,Waste - Wastewater Treatment:CH4,0.438294,2022,0.428962
64,trww,n2o,Waste - Wastewater Treatment:N2O,0.273529,2022,0.065935
65,waso,ch4,Waste - Solid Waste:CH4,1.145807,2022,1.009457
66,waso,co2,Waste - Solid Waste:CO2,0.574465,2022,0.000000
67,waso,n2o,Waste - Solid Waste:N2O,0.000698,2022,0.009818

In [62]:
report = sdr.generate_detailed_diff_report(draft_df, targets_df)
report

,Year,Subsector,Gas,Edgar_Class,Simulation_Values,Edgar_Values,diff
0,2022,agrc,ch4,AG - Crops:CH4,0.205360,0.000115,1781.464560
1,2022,agrc,co2,AG - Crops:CO2,1.268444,0.106978,10.857020
2,2022,agrc,n2o,AG - Crops:N2O,0.223638,1.300449,-0.828030
3,2022,ccsq,ch4,CCSQ:CH4,0.000000,0.000000,NaN
4,2022,ccsq,co2,CCSQ:CO2,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...
63,2022,trww,ch4,Waste - Wastewater Treatment:CH4,0.438294,0.428962,0.021754
64,2022,trww,n2o,Waste - Wastewater Treatment:N2O,0.273529,0.065935,3.148446
65,2022,waso,ch4,Waste - Solid Waste:CH4,1.145807,1.009457,0.135072
66,2022,waso,co2,Waste - Solid Waste:CO2,0.574465,0.000000,inf
67,2022,waso,n2o,Waste - Solid Waste:N2O,0.000698,0.009818,-0.928951

In [63]:
# report[(report['Subsector'] == 'ippu')]

In [64]:
df_1, df_2 = sdr.run_report_generator(simulation_df=output_df, emission_targets_path='misc/sectoral_reports/2022_emission_targets.csv', mapping_table_path='misc/sectoral_reports/edgar_ssp_cw.csv')

df_1

,Year,Subsector,Gas,Edgar_Class,Simulation_Values,Edgar_Values,diff
0,2022,agrc,ch4,AG - Crops:CH4,0.205360,0.000115,1781.464560
1,2022,agrc,co2,AG - Crops:CO2,1.268444,0.106978,10.857020
2,2022,agrc,n2o,AG - Crops:N2O,0.223638,1.300449,-0.828030
3,2022,ccsq,ch4,CCSQ:CH4,0.000000,0.000000,NaN
4,2022,ccsq,co2,CCSQ:CO2,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...
63,2022,trww,ch4,Waste - Wastewater Treatment:CH4,0.438294,0.428962,0.021754
64,2022,trww,n2o,Waste - Wastewater Treatment:N2O,0.273529,0.065935,3.148446
65,2022,waso,ch4,Waste - Solid Waste:CH4,1.145807,1.009457,0.135072
66,2022,waso,co2,Waste - Solid Waste:CO2,0.574465,0.000000,inf
67,2022,waso,n2o,Waste - Solid Waste:N2O,0.000698,0.009818,-0.928951

In [65]:
nesd = NonEnergySectoralDiffReport('misc/sectoral_reports', iso_alpha_3='HRV', init_year=2015, ref_year=2022)

In [ ]:
df_1, df_2 = nesd.run_report_generator(simulation_df=output_df, emission_targets_path='misc/sectoral_reports/2022_emission_targets.csv', mapping_table_path='misc/sectoral_reports/edgar_ssp_cw.csv')